/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include "stdlib.h"
#include <iostream>
#include "steffi.hpp"

//using namespace std;




int main()
{	
	int numb = 4*1000000; int fib=1; int c = 1; int b; int fibsum = 0;
	//std::cout << fib << std::endl;
	for(int a=1;fib<numb;a++){
	b = c + fib;
	c = fib;
	fib = b;
	//std::cout << fib << std::endl;
	if(fib%2==0){
	fibsum = fibsum + fib;
	std::cout << fibsum << std::endl;

	}
	}
	std::cout << fibsum << std::endl;



	return 0;		   // Anwendung beenden
}

